%YAML 1.2
---
train:
    num_epochs: 100
    learning_rate: 1.0e-4
    output_dir: ./dump_match_pairs/ # Path to the directory in which the .npz results and optional, visualizations are written during training
    dataset:
        batch_size: 6
        shuffle: false

        COCO:
            path: ./COCO2014/train2014
            fraction: 0.01
            resize: [640, 480] # [width, height] Resize the input image before running inference. Comment out if you don't want to resize
            fix_warp: false

        # ScanNet:
        #     path: ./ScanNet/train
        #     fraction: 0.001
        #     resize: [640, 480] # [width, height] Resize the input image before running inference. Comment out if you don't want to resize
        #     fix_warp: false

test:
    input_dir: ./assets/scannet_sample_images/ # Path to the directory that contains the images
    output_dir: ./dump_match_pairs_test/
    # input_pairs: ./assets/scannet_sample_pairs_with_gt.txt # Path to the list of image pairs for evaluation
    # eval_interval: 5 # evaluate 1 epoch every "eval_interval" training epochs

    dataset:
        batch_size: 16
        shuffle: false

        COCO:
            path: ./COCO2014/test2014
            fraction: 0.01
            resize: [640, 480] # [width, height] Resize the input image before running inference. Comment out if you don't want to resize
            fix_warp: true

        # ScanNet:
        #     path: ./ScanNet/eval
        #     fraction: 0.001
        #     resize: [640, 480] # [width, height] Resize the input image before running inference. Comment out if you don't want to resize
        #     fix_warp: true

feature_extraction:
    max_keypoints: 48 # Maximum number of keypoints
    descriptor_dim: 128 # Dimension of the descriptor
    extractor: SIFT

    SIFT:
        contrast_threshold: 0.0001
        edge_threshold: 10
        sigma: 1.6

    Superpoint:
        keypoint_threshold: 0.005 # SuperPoint keypoint detector confidence threshold
        nms_radius: 4 # SuperPoint Non Maximum Suppression (NMS) radius
        match_threshold: 0.1 # SuperGlue match threshold
        remove_borders: 4
        model_weight_path: ./models/weights/superpoint_v1.pth

perspective_warper:
    max_warp_match_pixel_distance: 2 # Maximum pixel distance between the matches to be considered for homography estimation
    warper: homography

    homography:
        perturbation_threshold: 0.1 # (0, 1.0] Perturbation threshold for homography matrix
        random_rotation: false

    nerf:
        novel_view_max_angle: 60 # Maximum angle (in degrees) between the new and old camera direction

superglue:
    sinkhorn_iterations: 100
    descriptor_dim: 128 # Dimension of the descriptor
    match_threshold: 0.1
    max_keypoints: 48
    batch_size: 1
    keypoint_encoder: [32, 64, 128]

# Visualize the matches and dump the plots
viz: true

# # Output directory for the visualization
# visualize_output_dir: ./dump_match_pairs/

# Plot the keypoints in addition to the matches
show_keypoints: true

# Resize the image after casting uint8 to float
resize_float: false

# Skip the pair if output .npz files are already found
cache: false

# Use faster image visualization based on OpenCV instead of Matplotlib
fast_viz: true

# png or pdf
viz_extension: png

# Visualize via OpenCV before saving output images
opencv_display: false

# Maximum number of pairs to evaluate
max_length: -1
