%YAML 1.2
---
train:
    num_epochs: 100
    learning_rate: 0.0001
    output_dir: dump_match_pairs/   # Path to the directory in which the .npz results and optional, visualizations are written during training
    dataset:
        batch_size: 6
        shuffle: false

        COCO:
            path: ./COCO2014/train2014
            fraction: 0.01
            resize: [640, 480] # [width, height] Resize the input image before running inference. Comment out if you don't want to resize
            fix_warp: false

        # ScanNet:
        #     path: ./ScanNet/train
        #     fraction: 0.001
        #     resize: [640, 480] # [width, height] Resize the input image before running inference. Comment out if you don't want to resize
        #     fix_warp: false

eval:
    input_dir: assets/scannet_sample_images/ # Path to the directory that contains the images
    output_dir: ./dump_match_pairs/
    input_pairs: assets/scannet_sample_pairs_with_gt.txt # Path to the list of image pairs for evaluation
    eval_interval: 5 # evaluate 1 epoch every "eval_interval" training epochs

    dataset:
        batch_size: 32
        shuffle: false

        COCO:
            path: ./COCO2014/eval2014
            fraction: 0.01
            resize: [640, 480] # [width, height] Resize the input image before running inference. Comment out if you don't want to resize
            fix_warp: true

        # ScanNet:
        #     path: ./ScanNet/eval
        #     fraction: 0.001
        #     resize: [640, 480] # [width, height] Resize the input image before running inference. Comment out if you don't want to resize
        #     fix_warp: true

feature_extraction:
    max_keypoints: 48 # Maximum number of keypoints
    descriptor_dim: 128 # Dimension of the descriptor

    extractor:
        SIFT:
            contrast_threshold: 0.0001
            edge_threshold: 10
            sigma: 1.6

        # Superpoint:
        #     keypoint_threshold: 0.005 # SuperPoint keypoint detector confidence threshold
        #     nms_radius: 4 # SuperPoint Non Maximum Suppression (NMS) radius
        #     match_threshold: 0.1 # SuperGlue match threshold
        #     remove_borders: 4
        #     model_weight_path: ./models/weights/superpoint_v1.pth

perspective_warper:
    max_warp_match_pixel_distance: 2 # Maximum pixel distance between the matches to be considered for homography estimation

    homography:
        perturbation_threshold: 0.25 # (0, 1.0] Perturbation threshold for homography matrix
        random_rotation: true

    # nerf:
    #     novel_view_max_angle: 60 # Maximum angle (in degrees) between the new and old camera direction

model:
    sinkhorn_iterations: 100
    descriptor_dim: 128
    match_threshold: 0.1
    max_keypoints: 48
    batch_size: 1
    keypoint_encoder: [32, 64, 128]
# superglue:
#     num_layers: 3
#     sinkhorn_iterations: 10
#     match_threshold: 0.2
#     descriptor_dim: 128 # Dimension of the descriptor

viz: true # Visualize the matches and dump the plots
# visualize_output_dir: ./dump_match_pairs/ # Output directory for the visualization
show_keypoints: true # Plot the keypoints in addition to the matches
resize_float: false # Resize the image after casting uint8 to float
cache: false # Skip the pair if output .npz files are already found
fast_viz: true # Use faster image visualization based on OpenCV instead of Matplotlib
viz_extension: png # png or pdf
opencv_display: False, Visualize via OpenCV before saving output images
max_length: -1 # Maximum number of pairs to evaluate
